### ISSUE TITLE
ONHITCASTSPELL Function not working

### ISSUE THREAD

**Issue by Ellirium113** [YenRaven/NWSetItemProperties#1]
In the example you posted here: ((https://github.com/YenRaven/NWSetItemProperties/blob/master/Capture.PNG))
I had copied to a suit of armor and a helmet to test. The light indeed turns on and dimly red however the ONHITCASTSPELL you have listed as "60" with an acceptable range between 0-140. The description shows "See IP_CONST_ONHIT_CASTSPELL_* for possible values" When you look down the list #60 is listed as IP_CONST_ONHIT_CASTSPELL_SOUND_BURST.
There does not seem to be any form of sound burst spell happening on hit or on a successful attack. I then tried to use integers from different spells and feats but had the same issue. In this example I tried to substitute FLAME STRIKE for SOUND BURST and got the same issue. The spell function does not apply.
![image](https://user-images.githubusercontent.com/69527578/89924962-59843480-dbc8-11ea-8df0-d71c7288b721.png)

**Comment by YenRaven** [comment]
Can you post the variables from the other items in the set?

**Comment by YenRaven** [comment]
Also, if you tick the `SET_TAG_0_BONUS_1_MIN_SET_ITEMS` up to 2, does the light effect still work?

**Comment by Ellirium113** [comment]
Tag had not saved on 2nd set of armor. Fixed. Please close issue.

**Comment by YenRaven** [comment]
For future people who might have a similar issue.

Issue was caused by a mismatched SET_TAG between the items in the set.  Remember to click "Replace" when updating variables!  An unfortunately bad bit of UX on the toolkits part.
