### ISSUE TITLE
Only the 1 item shows bonuses

### ISSUE THREAD

**Issue by Ellirium113** [YenRaven/NWSetItemProperties#2]
All of the variables are programmed onto a single item. Only on that item are the bonuses visible. How do you specify what bonuses are applied for specific items? Can separate items use different tag numbers in the same set so different effects can be applied for specific pieces? Example a 3 piece set helmet, sword, and armor should apply flaming sword effect when sword is equipped. Helmet using a dragon breath effect needs to be applied when the helmet is put on vs. the sword equipped. & vise versa.

**Comment by YenRaven** [comment]
I believe what you are looking for would look something like this...

On the armor variable set
|Name|type|value|
|----|----|----|
|SET_TAG_0|`string`|FIRE_SET_HELM_ARMOR|
|SET_TAG_1|`string`|FIRE_SET_SWORD_ARMOR|

Then on the sword
|Name|type|value|
|----|----|----|
|SET_TAG_0|`string`|FIRE_SET_SWORD_ARMOR|
|SET_TAG_0_BONUS_0_TYPE|`string`|ITEM_PROPERTY_VISUALEFFECT|
|SET_TAG_0_BONUS_0_MIN_SET_ITEMS|`int`|2|
|SET_TAG_0_BONUS_0_VISUALEFFECT|`int`|6|

And then on the helmet
|Name|type|value|
|----|----|----|
|SET_TAG_0|`string`|FIRE_SET_HELM_ARMOR|
|SET_TAG_0_BONUS_0_TYPE|`string`|ITEM_PROPERTY_CAST_SPELL|
|SET_TAG_0_BONUS_0_MIN_SET_ITEMS|`int`|2|
|SET_TAG_0_BONUS_0_CAST_SPELL|`int`|403|
|SET_TAG_0_BONUS_0_USES|`int`|13 |

The key point being the armor belongs to two sets, one with the helm and another with the sword.
